# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|


  config.vm.box = "minimal/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    sync_folder(config)
    forward_port(config)
  end

  def forward_port(config)
    config.vm.network "forwarded_port", guest: 8081, host: 8081

  end
  def sync_folder(config)
    config.vm.synced_folder "install_scripts/", "/tmp/scripts"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
bash /tmp/scripts/install-base.sh
   bash /tmp/scripts/install-oracle-jdk.sh
   bash /tmp/scripts/install-keycloak-wrapper.sh
  SHELL
end
